-- OAuth2 Initialization Data Script (init.sql)

-- Clean up existing test data (optional)
--DELETE FROM oauth2_authorization_consent;
--DELETE FROM oauth2_authorization;
--DELETE FROM oauth2_registered_client;
--DELETE FROM oauth2_jwt_keys;

-- Create test client
--INSERT INTO oauth2_registered_client (
--    id,
--    client_id,
--    client_id_issued_at,
--    client_secret,
--    client_secret_expires_at,
--    client_name,
--    client_authentication_methods,
--    authorization_grant_types,
--    redirect_uris,
--    post_logout_redirect_uris,
--    scopes,
--    client_settings,
--    token_settings
--) VALUES (
--    '4173994d-0e69-42e0-9b8f-5d70a3e2d684', -- UUID
--    'messaging-client', -- Client ID
--    CURRENT_TIMESTAMP, -- Client ID issued at
--    '{noop}secret', -- Client secret (with encoding hint)
--    NULL, -- Client secret expires at (NULL means never expires)
--    'Messaging Client', -- Client name
--    'client_secret_basic', -- Authentication method
--    'client_credentials', -- Authorization grant type
--    NULL, -- Redirect URIs (not needed for client credentials flow)
--    NULL, -- Post logout redirect URIs
--    'message.read', -- Scope
--    '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}', -- Client settings JSON
--    '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":"RS256","settings.token.access-token-time-to-live":"PT300S","settings.token.refresh-token-time-to-live":"PT1800S","settings.token.authorization-code-time-to-live":"PT300S"}' -- Token settings JSON
--);

-- Create another client with authorization code flow (optional)
--INSERT INTO oauth2_registered_client (
--    id,
--    client_id,
--    client_id_issued_at,
--    client_secret,
--    client_secret_expires_at,
--    client_name,
--    client_authentication_methods,
--    authorization_grant_types,
--    redirect_uris,
--    post_logout_redirect_uris,
--    scopes,
--    client_settings,
--    token_settings
--) VALUES (
--    '6236aa2a-fd50-4c7b-ae2d-f427b61db9b9', -- UUID
--    'web-client', -- Client ID
--    CURRENT_TIMESTAMP, -- Client ID issued at
--    '{noop}web-secret', -- Client secret (with encoding hint)
--    NULL, -- Client secret expires at (NULL means never expires)
--    'Web Client', -- Client name
--    'client_secret_basic', -- Authentication method
--    'authorization_code,refresh_token', -- Authorization grant type
--    'http://localhost:8080/authorized,http://localhost:8080/login/oauth2/code/web-client', -- Redirect URIs
--    'http://localhost:8080/logged-out', -- Post logout redirect URIs
--    'openid,profile,message.read,message.write', -- Scope
--    '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":true}', -- Client settings JSON
--    '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":"RS256","settings.token.access-token-time-to-live":"PT900S","settings.token.refresh-token-time-to-live":"P7D","settings.token.authorization-code-time-to-live":"PT300S"}' -- Token settings JSON
--);

-- Can pre-create a JWT key (optional, system will auto-create)
-- Below uses a sample key, actual application should generate a new key
--INSERT INTO oauth2_jwt_keys (
--    id,
--    key_id,
--    public_key,
--    private_key,
--    issue_date,
--    is_active
--) VALUES (
--    '79e20a02-64cf-48eb-b8a8-511357b258a4', -- UUID for record ID
--    '2023-key-id', -- Key ID
--    'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArYaYlKnGcKUJWcIp7k4zWq6EqwLLExQn8m9ENBnKKzMvNdJl+yqNHALJIZlHCdWcXX8y8+ByU4hklFdvIYKxJJMH9Bq1YcXbS8vQZ4YyYSTNe/IMvSJR1ujPK4/PjXx6nxf1rEgb5qV5yvpjfBkWF6AYMSLnxbKZmuATH+6qVNyuLQduCCHRGC9i8vhZi5hQp2/yWLmtt7sYIBTrY/GgJzF9g3EFx8nGQTBUWbHFSFfLm3K2BaC5r8QOjaorIcfXUCDx0sbD1J5tScZRnj8iCvpTMWEUrh6fJzYKHx6jBgS2xIVSQTSXY+VElYCCUxg3qdvXCiQMey0lbNiPKS3jjwIDAQAB', -- Base64 encoded RSA public key
--    'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCthpiUqcZwpQlZwinuTjNaroSrAssTFCfyb0Q0GcorMy810mX7Ko0cAskhmUcJ1ZxdfzLz4HJTiGSUV28hgrEkkwf0GrVhxdtLy9BnhjJhJM178gy9IlHW6M8rj8+NfHqfF/WsSBvmpXnK+mN8GRYXoBgxIufFspma4BMf7qpU3K4tB24IIdEYL2Ly+FmLmFCnb/JYua23uxggFOtj8aAnMX2DcQXHycZBMFRZscVIV8ubcrYFoLmvxA6Nqishx9dQIPHSxsPUnm1JxlGePyIK+lMxYRSuHp8nNgofHqMGBLbEhVJBNJdj5USVgIJTGDep29cKJAx7LSVs2I8pLeMPAgMBAAECggEBAKttHT2rizvBYsGNxVQjyZ5g7QHgJjUVCDf9h2CcIEh1kNYW9hsJ+FqZQhZhc4eR4vRW9UGZrpUuNZVmJPrM8G1eRbd2BWGjKqhv5XqxdCyGJfJZ7dXjZMTZbr6YtcVcnBsJsasYsozRRWCnM21iiCrzw+ptFAjj63MXMhUJELQPOsIVNxDYaGFtYc6CziYSDYTtMN6MKVDPcK9D9O/OIwOQQHjrVQrQyJgCt5qTIzHP/T2JQwFIRHSAYHJrZPPNvvbNA9ym7JqZXQpG/nvkROdVTnWBUgSA7LtD+BwK3AEYsJyEL1K7IB+mFP71peJnY32A4FRqVnwzVTLyfQREYQECgYEA5t4UDRzLx/QIxtA2s1xhGxG312h4zxFGGgkGxJJkJQEe0+s5wXzHGu3QHpKcpzrJvX8BEZIHx0u5B8u0wMFKEYi5ZNO7dqLuP5/JY5KfOvpSQsJQXrX9brzKjhEJY75UWestVQrpbQp3jpKiKNXHUTzIz8MOv1C0J8gZHZce/0ECgYEAwO8PKcJpkB2h2dIlccwluMH/hd7jGVkaGZoJZ8qBvUuLcWcq1vJ+gQENL6Y39QDbgkXZGzKgdOAWQbzLiAJp5sHRPrnzMdI2LmEcRLZMeQE7CKsIRlGtVFpZ1cqWCZmS3F9+qAdEd6uKVCaoGQ1/edcR/FrYKQIazqcqveUypI8CgYB6ZF+tnQJ+ZjLkfLcf9DnYhGDVxGlQdl4jEQCkWDJknf54z2l6J+M90epbjVYKhOQoI2bIEQTgVUAFGgTC3Vwc7+jUQROCno3RS8nY5/7jgLDLncNvRz9lKxsZh8Tq3VNvI5gCUzWR+eNPXnUPXHEeHCu+4v8haz8xiy+ebDTaQQKBgHnVRKGCMyLDtGzCJQFUhdwzIbI9gUyOLVFfImrnHfwXSQDcyvJt8Go6Ub3Ri5F9J200/4o8XY+C+9y+pJ7ERDSUMVKoqwvhAtZtUZ/Xk8KPq1mfmPXdULqKy5n4G6KLZaMTBg7EKrjL9g9pqNHOvYsQ+6LEZVXJisJQDnY+nQajAoGBALZfxC1EDWeXQxgLZuLs5xijOosOhQyXrS2ERjzaUfBP91L9uZj7QMCc5aNnuHsQM+Ll3jcOjkUIBnpjZo0YEDUMsk+E9IvuOC4RBhLMIrb2NCwPgCUWx8iiJqmLZPu7n2aZfZsTbQN8drsL9mTR6QZPZ0Z5deytk9tXiXiM5hgE', -- Base64 encoded RSA private key
--    CURRENT_TIMESTAMP, -- Issue date
--    TRUE -- Is active
--);

-- Add authorization consent record (optional, usually created when user authorizes)
--INSERT INTO oauth2_authorization_consent (
--    registered_client_id,
--    principal_name,
--    authorities
--) VALUES (
--    '6236aa2a-fd50-4c7b-ae2d-f427b61db9b9', -- web-client's ID
--    'user', -- User name
--    'SCOPE_openid,SCOPE_profile,SCOPE_message.read' -- Authorized scope
--);
