server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          opaque-client:
            provider: spring
            client-id: opaque-client
            client-secret: opaque-secret
            authorization-grant-type: client_credentials
            scope: message.read
          jwt-client:
            provider: spring
            client-id: jwt-client
            client-secret: jwt-secret
            authorization-grant-type: client_credentials
            scope: message.read
        provider:
          spring:
            token-uri: http://localhost:9000/oauth2/token

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG 