server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema/oauth2-schema.sql
#      data-locations: classpath:schema/init.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
  application:
    name: api-auth-server

# 密钥库配置
app:
  jwt:
    keystore:
      path: mykeystore.jks
      password: mykeystorepass
      key-alias: myalias
      key-password: mykeypass
oauth2:
  migration:
    enabled: true
    legacy-server:
      url: http://localhost:9001
      username: admin
      password: admin123