server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
        opaquetoken:
          # The resource server does not need to specify scope in the configuration because:
          # scope is the range of permissions allowed for the client, which has already been configured for this client (resource-server) in the authorization server
          # When the resource server makes an introspection request, it is only verifying a token, not requesting new access permissions
          # The introspection process is done by sending client credentials using basic authentication, followed by sending the token for verification
          # The OAuth2 resource server module of Spring Security automatically handles this process, so there is no need to explicitly specify scope in the resource server configuration. The scope configuration only needs to be completed on the authorization server side.
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: resource-server
          client-secret: secret

logging:
  level:
    org.springframework.security: DEBUG 