server:
  port: 8081

oauth2:
  server:
#    token-uri: http://localhost:9001/oauth/token  # legacy auth server
    token-uri: http://localhost:9000/oauth/token  # new auth server with legacy API
  client:
    jwt:
      client-id: jwt-client
      client-secret: jwt-secret

api:
  server:
    url: http://localhost:8091

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG 