server:
  port: 8091

security:
  oauth2:
    resource:
      id: jwt-client-resource-id
      jwt:
        key-uri: http://localhost:9000/oauth/token_key
      prefer-token-info: true

logging:
  level:
    org.springframework.security: DEBUG 