server:
  port: 8091

security:
  oauth2:
    resource:
      id: legacy-api
      jwt:
        key-uri: http://localhost:9001/oauth/token_key
      prefer-token-info: true

logging:
  level:
    org.springframework.security: DEBUG 